export const environment = {
  production: false,
  apiUrl: "http://localhost:8080/",
  apiEndpoints: {
    login: "api/login/",
    register: "api/register/",
    user: "user/",
    username: "user/username/",
    locuinte: "locuinte/",
    type: "type/",
    proprietary: "proprietary/",
    favorite: "favorite/",
    news: "news/",
    reservation: "reservation/",
    make_reservation: "reservation/create/",
    available: "reservation/available/",
    active: "reservation/active/",
    stat: "reservation/stats/",
  },
};
