# Generated by Django 4.1.7 on 2023-04-08 21:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
