# Generated by Django 4.1.7 on 2023-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locuinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Vanzare'), (2, 'Inchiriere')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Garsoniera'), (2, 'Apartament1'), (3, 'Apartament2'), (4, 'Apartament3'), (5, 'Apartament4'), (6, 'Casa'), (7, 'Spatiu_birouri'), (8, 'Spatiu_comercial')], default=1)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0, max_length=8)),
                ('square_meters', models.IntegerField(default=0)),
                ('floor', models.CharField(blank=True, default='', max_length=2)),
                ('rooms', models.CharField(blank=True, default='', max_length=2)),
                ('city', models.CharField(default='', max_length=20)),
                ('zone', models.CharField(default='', max_length=30)),
                ('date_added', models.DateField(auto_now=True)),
                ('promoted', models.BooleanField(default=False)),
            ],
        ),
    ]
