# Generated by Django 4.1.7 on 2023-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliare', '0002_alter_locuinta_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='locuinta',
            name='img_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
