# Generated by Django 4.1.7 on 2023-05-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliare', '0006_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='house',
            new_name='locuinta',
        ),
    ]
